### ISSUE TITLE
Minio client does not support bucket prefix

### ISSUE THREAD

**Issue by rfaircloth-splunk** [reportportal/service-auto-analyzer#42]
When using S3 rather than minio the client attempts to create one bucket per project proj-x format which is unsafe.

The request is to use a single bucket specified as a env var and create objects in paths inside the bucket this is also better for a minio shop

**Comment by MariyaIvanina** [comment]
Hi, @rfaircloth-splunk! Our report-portal backend creates prj-x buckets for each project to save attachments and some other info, that's why I used this convention to create the bucket if it doesn't exist and save some analyzer information there. Could you please describe your suggestion in a more detail? As far as I didn't quite understand it. Thank you in advance!

**Comment by MariyaIvanina** [comment]
Hi, thanks for reporting this issue. I've added ANALYZER_BINARYSTORE_BUCKETPREFIX  environmental variable, so you can override prefix now. This is available in 5.3.4 version, I've just released it. You can also see other available environmental variables here https://github.com/reportportal/service-auto-analyzer/blob/develop/README.md
